### DISCUSSION TITLE
Easier AppImage generation

### DISCUSSION THREAD

**Discussion by ghost** [Bforartists/Bforartists#3187] [General]
I made this yml script out of Blender script for pkg2appimage tool
no need to download or store the heavy virtual machine :)
it also uses the BFORARTISTS_VERSION variable, and doesn't need the special virtual machine
this script gets executed using pkg2appimage tool

```
wget -c https://github.com/$(wget -q https://github.com/AppImage/pkg2appimage/releases -O - | grep "pkg2appimage-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
chmod +x ./pkg2appimage-*.AppImage
./pkg2appimage-*.AppImage Bforartists.yml
```

Bforartists.yml file
```yml
app: Bforartists

ingredients:
  script:
    - wget -c "https://github.com/Bforartists/Bforartists/releases/download/v${BFORARTISTS_VERSION}/Bforartists-${BFORARTISTS_VERSION}-Linux.tar.xz"
    - mkdir -p bforartists
    - tar xf Bforartists*.tar.xz -C ./bforartists --strip-components=1

script:
  - cp -r ../bforartists/* ./usr/bin/;
  - cp ./usr/bin/bforartists.svg .
  -
  - cat > bforartists.desktop <<\EOF
  - [Desktop Entry]
  - Name=Bforartists
  - GenericName=3D modeler
  - Comment=3D modeling, animation, rendering and post-production
  - Keywords=3d;cg;modeling;animation;painting;sculpting;texturing;video editing;video tracking;rendering;render engine;cycles;game engine;python;
  - Exec=bforartists %f
  - Icon=bforartists
  - Terminal=false
  - Type=Application
  - Categories=Graphics;3DGraphics;
  - MimeType=application/x-bforartists;
  - EOF
```

**Comment by ReinerBforartists** [comment]
Usage ?

**Reply by ghost** [reply]
What is usage meaning?

**Comment by ReinerBforartists** [comment]
How do i use your easier method? How does it work? Where to put the xml? :)

**Comment by ghost** [comment]
1. put this code into a .yml file, for example `Bforartists.yml`

```yml
app: Bforartists

ingredients:
  script:
    - wget -c "https://github.com/Bforartists/Bforartists/releases/download/v${BFORARTISTS_VERSION}/Bforartists-${BFORARTISTS_VERSION}-Linux.tar.xz"
    - mkdir -p bforartists
    - tar xf Bforartists*.tar.xz -C ./bforartists --strip-components=1

script:
  - cp -r ../bforartists/* ./usr/bin/;
  - cp ./usr/bin/bforartists.svg .
  -
  - cat > bforartists.desktop <<\EOF
  - [Desktop Entry]
  - Name=Bforartists
  - GenericName=3D modeler
  - Comment=3D modeling, animation, rendering and post-production
  - Keywords=3d;cg;modeling;animation;painting;sculpting;texturing;video editing;video tracking;rendering;render engine;cycles;game engine;python;
  - Exec=bforartists %f
  - Icon=bforartists
  - Terminal=false
  - Type=Application
  - Categories=Graphics;3DGraphics;
  - MimeType=application/x-bforartists;
  - EOF
  ```
  
  2. download pkg2appimage
  `wget -c https://github.com/$(wget -q https://github.com/AppImage/pkg2appimage/releases -O - | grep "pkg2appimage-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)`
  
  3. make it executable
  `chmod +x ./pkg2appimage-*.AppImage`
  
  4. Build AppImage (the tar has to be uploaded to github just like the old appimage way)
  `BFORARTISTS_VERSION=3.2.2 ./pkg2appimage-*.AppImage Bforartists.yml`
