### ISSUE TITLE
Update Windows Github actions script to be relative

### ISSUE THREAD

**Issue by happymimimix** [Bforartists/Bforartists#4848]
Windows used back slash '\\' for directory separation! Not forward slash '/'. 
Your build script used the forward slash '/' which is unacceptable in Microsoft Windows! 
The script mysteriously still works however, I have no idea how it still managed to upload a working windows build while we can clearly see windows non-stop complaining about the use of '/' in the build logs. 
![image](https://github.com/user-attachments/assets/c7edde15-cf7f-4bd6-835b-dac602597198)

Also, your build script used absolute paths like C:\Users\runneradmin, which is also a very bad practice! How can you be 100% sure that the username of the runner's machine is runneradmin? You should use relative paths and environment variables to make sure the script works on every machine! 
%CD% gives you the current directory. 
%systemdrive% gives you the drive letter that the system currently runs on. 
The drive letter is not always C:, it could also be Z:, X:, A:, D:, or any other letter! 
%username% gives you the name of the current user. 
%userprofile% give you the directory of the user profile
In addition, not every windows computer has a D: drive! 
A windows computer could have only one C: drive and nothing else, and it would still work just fine. 
You should always check whether the D: drive exists or not before using it in the build. 

To avoid any potential issues with windows builds in the future, I strongly recommend you correct these mistakes in your build script.

**Comment by ReinerBforartists** [comment]
Hey happymimimix,

Many thanks for the report and the hint. We will have a look at it and fix it asap :)
You could make a pull request if you want and have the time for :)
Kind regards
Reiner

**Comment by happymimimix** [comment]
> Hey happymimimix,
> 
> Many thanks for the report and the hint. We will have a look at it and fix it asap :) You could make a pull request if you want and have the time for :) Kind regards Reiner

Let me take a closer look at why this seemingly incorrect script CAN build in the first place. 
This should've gone into a compilation error, at least that's what I was expecting. 
But no, it actually made a working windows build!

**Comment by happymimimix** [comment]
> Hey happymimimix,
> 
> Many thanks for the report and the hint. We will have a look at it and fix it asap :) You could make a pull request if you want and have the time for :) Kind regards Reiner

According to what I found in the logs, this is what actually happened during the build: 

First, the command ```mkdir C:/Users/runneradmin/bforartistsrepo``` is executed. 
Since you incorrectly used forward slash '/' in the command, the command actually does nothing and throws the ```The syntax of the command is incorrect.``` error. 

Then, the command ```cd C:/Users/runneradmin/bforartistsrepo``` is executed. 
Since the previous command didn't run correctly, the directory ```C:\Users\runneradmin\bforartistsrepo``` is not being created. The use of forward slash in the CD command doesn't cause any problem because of how this command was implemented. Forward slash and backward slash work exactly the same here. 

Then, the command ```git clone https://github.com/Bforartists/Bforartists``` is executed. 
Everything in this github repo is being downloaded into ```.\Bforartists```. Since the previous two commands failed to execute, this command puts the repo into the current directory instead of ```C:\Users\runneradmin\bforartistsrepo\Bforartists```. In your case, it's ```D:\a\Bforartists```. 

After that, the actual build process begins. Which didn't cause any problem because of how Windows process the path names. 
Windows implemented the forward slash typo rescuing logic everywhere but ```mkdir```! Very weird. 

After the build process completes, three more commands that does absolutely nothing were executed. I don't know if they are there for debugging purpose or what. But here's what they actually do: 
```dir``` -> List the content of the current directory on screen
```cd ..``` -> Go to the previous directory
```dir``` -> List the content of the current directory on screen again
Besides adding a few lines of additional text to the build logs, these three lines does absolutely nothing. 

Then it started the upload process. Here, you specified two paths that needs to be uploaded. 
```C:/Users/runneradmin/bforartistsrepo/bfa_build_windows_x64_vc17_Release/bin```
and
```D:/a/Bforartists/Bforartists/bfa_build_windows_x64_vc17_Release/bin```
The first one obviously doesn't work because of what we discussed earlier. 
However, the second one does work because the build process is actually done inside ```D:/a/Bforartists``` the entire time! Not inside ```C:\Users\runneradmin\bforartistsrepo\Bforartists```. 

As a result, you do get a working Windows build being uploaded to github even with all of these mistakes in your script. 


A cleaner approach would be as follows: 
```
name: Windows

on:
  #push:
    #branches: [ master ]
  schedule:
    - cron: 0 0 * * 1
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions: {}
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: make
      shell: cmd
      run: |
        git clone https://github.com/Bforartists/Bforartists
        cd Bforartists
        python .\build_files\utils\make_update.py
        make


    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: Bforartists-Release-${{ runner.os }}
        path: D:\a\Bforartists\Bforartists\bfa_build_windows_x64_vc17_Release\bin
```
I don't know how to use windows environment variables in the upload build process. Github immediately gives me a syntax error when I tried to do that. 
If possible, it would be even better if you do this: 
```
name: Windows

on:
  #push:
    #branches: [ master ]
  schedule:
    - cron: 0 0 * * 1
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions: {}
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: make
      shell: cmd
      run: |
        mkdir %userprofile%\bforartistsrepo
        cd %userprofile%\bforartistsrepo
        git clone https://github.com/Bforartists/Bforartists
        cd Bforartists
        python .\build_files\utils\make_update.py
        make

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: Bforartists-Release-${{ runner.os }}
        path: %userprofile%\bforartistsrepo\Bforartists\Bforartists\bfa_build_windows_x64_vc17_Release\bin
```
